### ISSUE TITLE
Installing Hoodie doesn't work on mac

### ISSUE THREAD

**Issue by hem31831** [hoodiehq/faq#109]
Hi,

I tried to install Hoodie on my fresh installed mac. Using the linked npm package and so on. The result
is that 

npm install -g hoodie-cli doesn't work

It seems that this is caused by insufficient privileges. I found the tip in the known error section
to use the change owner command:

Matthiass-MacBook-Pro:~ mh$ sudo chown -R $mh /usr/local/lib/node_modules
Password:
usage: chown [-fhv] [-R [-H | -L | -P]] owner[:group] file ...
       chown [-fhv] [-R [-H | -L | -P]] :group file ...
Matthiass-MacBook-Pro:~ mh$ npm install
npm ERR! install Couldn't read dependencies
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! path /Users/mh/package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno -2

npm ERR! package.json ENOENT, open '/Users/mh/package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mh/npm-debug.log

-------

What can I do to make it work?

**Comment by zoepage** [comment]
`npm install` can't work, because you don't have any app with a package.json in it. This just workes for the case described in here http://faq.hood.ie/#/question/38210259 as you've mentioned it. :)

Could you please try `npm install -g hoodie-cli` now? :)
