### ISSUE TITLE
Problems using external CouchDB

### ISSUE THREAD

**Issue by saschazar21** [hoodiehq/faq#114]
I tried to use a CouchDB hosted on Iriscouch, without installing a local CouchDB on my Mac. According to [this](http://faq.hood.ie/#/question/46383743) FAQ-section, I set the environment variables to the following:

```
export COUCH_URL="mydb.iriscouch.com:5984"
export HOODIE_ADMIN_USER="admin"
export HOODIE_ADMIN_PASS="mysecretpassword"
```

I made sure to create an admin-user on the remote CouchDB, so that everything should work - although when I start my hoodie app, it always hangs on the non-existent local CouchDB-initialization.

Is there a way to get around this?

**Comment by janl** [comment]
try `export COUCH_URL="https://mydb.iriscouch.com:5984"`

**Comment by saschazar21** [comment]
hmm.. tried that, but it still exits while trying to connect to CouchDB.
![couchdb_fail](https://cloud.githubusercontent.com/assets/9016897/8512404/d20778f4-2340-11e5-87a1-a27cfdc7d6a7.png)

*couch.stderr* says the following (because, obviously, a local CouchDB-install is non-existent):

```
line 4: cd: /Contents/Resources/couchdbx-core: No such file or directory
line 5: ./bin/couchdb: No such file or directory
line 4: cd: /Contents/Resources/couchdbx-core: No such file or directory
line 5: ./bin/couchdb: No such file or directory
line 4: cd: /Contents/Resources/couchdbx-core: No such file or directory
line 5: ./bin/couchdb: No such file or directory
line 4: cd: /Contents/Resources/couchdbx-core: No such file or directory
line 5: ./bin/couchdb: No such file or directory
```

**Comment by janl** [comment]
can you show a full list of commands that you are running to start Hoodie?

**Comment by saschazar21** [comment]
Okay, thanks a lot here - unfortunately it was all my bad. 
I was setting the environment variables via a shell script, like this.
```
#!/bin/sh

###########
#
# Set environment variables for geoparse hoodie project
#
###########

echo 'Setting environment variables...'

export COUCH_URL="http://mydb.iriscouch.com:5984"
(...)
```
But I only executed it via `./env.sh`, and the environment variables didn't get set globally.
Call the script with `source ./env.sh`, and everything gets set correctly.

Hoodie is now connecting fine to the remote CouchDB.

Again, thanks a lot. Hope it helps somebody else, who's trying to work only on a remote CouchDB...

**Comment by janl** [comment]
Glad it’s working for you now! :)

**Comment by espy** [comment]
Added to our FAQ, thanks for posting your solution!
