### ISSUE TITLE
Pages Slow to Load and Updating

### ISSUE THREAD

**Issue by psmod2** [hoodiehq/faq#120]
Hello,

I'm finding that pages are very slow to load, for example I have a login page which should ascertain with the user is logged in or not using the standard hoodie method - however it takes around 30 secs - 1 min.
Its the Waiting (TTFB) thats 57 seconds.

I've asked this on StackOverflow and am told its a bug you are working on.

Based on this:
1- Any update on a fix for this?
2- One a fix is available how does one update the version of hoodie used? (This I now believe is simply a npm update - but if you could still confirm that would be appreciated).

Thanks,

**Comment by espy** [comment]
Hi there,

we do have one problem where the `hoodie.js` file is built server-side, and that's pretty slow, but that's also at an earlier point than what you describe, and I've never seen it take anywhere near that long. Is that page public somewhere so we can take a look?

Thanks!

As an aside, if it is that compilation feature: that will go away in the upcoming 1.0. However, that's not going to be a fix, it's a whole new version that, while improving mountains of stuff, also breaks some things, I'm afraid. We'll document upgrading when we release, though.

**Comment by psmod2** [comment]
Hi,

Ok, will keep an eye on - and the page isn't public, its for an internal app.

Thanks.

**Comment by psmod2** [comment]
I just did some more debugging and the delay is on the hoodie.js file itself with the 1.8min wait being on the latency.

Any immediate fixes for this or wait for the update?

**Comment by gr2m** [comment]
>  Can i just copy this and save locally as a temp solution or would that break anything?

Yes. You only need to re-download it whenever you add or remove hoodie plugins

**Comment by Guria** [comment]
Also experiencing long loading of `hoodie.js`
You can check it yourself on:

app: https://hoodie-test-guria.c9users.io/
server-side terminal https://hoodie-test-guria.c9users.io/

**Comment by gr2m** [comment]
yeah that is a known issue, it’s like that on the first two loads, but then it’s fast. It will be fixed with the new version

**Comment by abunet** [comment]
HI, any news with this issue? I'm experiencing similar problem on a raspberry pi 3.
2016-05-28T20:35:19.908Z [] GET 200 /_api/_files/hoodie.js 84783ms

**Comment by psmod2** [comment]
Hey - I'm not sure if hood.ie team fixed - the project I used it on closed however to solve it I simply made a copy of the file and referenced that version.

**Comment by gr2m** [comment]
@abunet This is fixed in the new Hoodie Version. Try to setup our tracker app to see how it works:
https://github.com/hoodiehq/hoodie-app-tracker#setup

The new hoodie is not compatible with the old one, but we are working on a migration script, stay tuned :)
