### ISSUE TITLE
Docker workflow for hoodie?

### ISSUE THREAD

**Issue by jkaplon** [hoodiehq/faq#129]
Hi all, I'm here after listening to the FLOSS Weekly podcast episodes covering CouchDB and Hoodie.
Nice place you've got here.
I hope this is the right place to post my questions.

I'm trying to find a good Docker setup for Hoodie, and it's been more difficult than I expected.
There is this "try out Hoodie, but DO NOT use in production" Dockerfile, https://github.com/caolan/docker-hoodie.
It's straightforward, but hasn't been updated in 2 years.
The Hoodie image that has the most pulls on Docker Hub is part of what looks like a serious/production-level fleet of images, https://github.com/greenlizard/docker-images/tree/master/hoodie.
I've pulled this Hoodie image and the associated CouchDB image, the CouchDB image runs fine, but I get an error with `hoodie start`.
It looks like the hoodie image has the current version of hoodie-cli (0.6.3), but I find it concerning that the listed version of node.js is a year out of date (0.10.37).

Anyone else have better luck with the greenlizard images?
Are there others in the hoodie community rolling their own Docker images?
I'm a "weekend-warrior web developer" who would like to evaluate Hoodie for use on side-projects and Docker is an important part of the process for me.
The docs are more focused on running hoodie in a local-PC development environment, and they thin out when it comes to server deployment.
So I think some more current Docker-related artifacts might come in handy.
I might be able to help out, but if I'm headed in the wrong direction with all this, feel free to set me straight.

**Comment by gr2m** [comment]
Hey @jkaplon, I would recommend to use our new Hoodie that we will release soon. It’s pretty stable already, and much easier to setup and debug. You can use this app as a starting point: https://github.com/hoodiehq/hoodie-app-tracker

It has a Docker file and a continuous deployment setup with Digital Ocean, see https://github.com/hoodiehq/hoodie-app-tracker/blob/master/deployment.md

**Comment by jkaplon** [comment]
Thanks @gr2m, that's just what I needed.
And it even comes with a sample LetsEncrypt configuration...I'm impressed.

I wish I'd explored that repo sooner, but there are so many hoodiehq repositories, the tracker app didn't jump out at me.

**Comment by gr2m** [comment]
@jkaplon we know :( we are right now in this weird state between the current Hoodie and the really nice and shiny new version, and all the website etc has not yet been updated. Best is to come to our [Hoodie Chat](http://hood.ie/chat/), we will point you to the right directions
