### ISSUE TITLE
How does Hoodie handle the caching mechanism?

### ISSUE THREAD

**Issue by micsag** [hoodiehq/faq#136]
Is Hoodie using any plugins for caching the application or is it using ServiceWorkers to do that? Can you explain me the exact mechanism.

**Comment by gr2m** [comment]
Hoodie is not caching any assets, only data. You can use ServiceWorker or applicationCache to cache your app’s assets like HTML files or images. 

But what you can check out is our tutorial at http://camp-tutorial.hood.ie, it combines ServiceWorker with Hoodie to show how the two work together.

Does that answer your question?

**Comment by micsag** [comment]
Thank you, now it´s clear to me.
