### ISSUE TITLE
Why no App Cache support?

### ISSUE THREAD

**Issue by pd-giz-dave** [hoodiehq/faq#139]
Sorry if this is in the wrong place, I'm a bit naive when it comes this sort of thing.
I want to develop a web app that works off-line, and when I found hood.ie I thought "yippee".
But then I discover its only data off-line and not assets.
I must be missing something?
If you fire up a browser with no internet connection, without the app cache, you're not going to get anywhere, data held locally or not.
What am I missing?
I found hoodie-plugin-appcache but that seems to be defunct.

**Comment by gr2m** [comment]
no worries this place is just fine to ask a question.

You are correct, Hoodie is only for Offline Data. The good news: this is the hard part, caching your app assets to work offline is much simpler.

`hoodie-plugin-appcache` is no longer working with the new Hoodie. Also [Application Cache is deprecated](https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache), you should use Service Workers instead. A simple library you could look into is https://www.talater.com/upup/. We also created a little tutorial that walks you trough Hoodie and also Service Worker: https://camp-tutorial.hood.ie/ – this app works entirely offline, source code is at https://github.com/hoodiehq/hoodie-camp-tutorial

Note that Service Worker is not yet supported on iOS and Safari on Desktop. If you need iOS / Safari desktop support you need to implement Application Cache. I wrote a library that you might find helpful: https://github.com/gr2m/appcache-nanny/

Does that help?

**Comment by pd-giz-dave** [comment]
Aha! It all makes sense now. I didn't realise the application cache feature
itself was being deprecated. I'm now learning about service workers. Thanks
for the pointer.
