### ISSUE TITLE
Is there anything to be considered when using Hoodie together with PhoneGap/Cordova?

### ISSUE THREAD

**Issue by boennemann** [hoodiehq/faq#19]
No, there are no problems with [PhoneGap](http://phonegap.com/)/[Cordova](https://cordova.apache.org/) we can currently think of. It should just work™.

**Comment by mikehedman** [comment]
Hi,
The question I'd like to ask is how to deal with /_api/_files/hoodie.js.  That file **wants** to be served up dynamically, but in Cordova I would want to have that bundled in with my app.  What I have done is to just grab a copy that has been previously served up for my app, and it works when running in a browser (have not yet tried in Cordova, but it should be fine).  But I'm not sure if making that dynamic hoodie.js file a static file is OK to do.

**Comment by janl** [comment]
@mikehedman you got it right. Bundling your own hoodie.js file is totally fine, and yes, you need to update it whenever you add a plugin on the server.

**Comment by mikehedman** [comment]
Thanks!
