### ISSUE TITLE
How to debug a plugin's backend code?

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/faq#28]
We recommend to use [node-debug](http://nodejs.org/api/debugger.html). Instead of starting your app with the plugin using the `hoodie start` command, use the command below

```
$ node-debug node_modules/hoodie-server/bin/start
```

**Comment by cdeadlock** [comment]
How to debug in the Test framework context?

For example I downloaded the hoodie-plugin-template, wrote some code in the 
worker.js
installed phantomjs, and I want to run the 
grunt test 
with a breakpoint set

**Comment by cdeadlock** [comment]
I got the grunt-mocha-debug package to work with the 
```
grunt:test
```
unit testing of the hoodie-plugin-template repository.

But I can't seem to figure out how the phantomJS, and mocha-browser would work with debugging.

**Comment by gr2m** [comment]
Hey, could you open an issue on the hoodie-plugin-template repository, as this issue is already closed?
