### ISSUE TITLE
Search in a property of an Object

### ISSUE THREAD

**Issue by cbuchler** [hoodiehq/faq#35]
When I save data via hoodie.store. 
Is there any way I can search for a property inside of that object? 
Current methods on hoodie.store only mention "findOrAdd" and "FindAll" 

If it isn't implemented is there a roadmap to implement this?

**Comment by wajerrr** [comment]
I am not sure if you aware but this feature is not in API docs. which I guess renders almost unusable (and can cause repeated feature request,s  etc.)

sorry don't want to be a pain
I know it Hoodie is in early stage of dev.

**Comment by jmatsushita** [comment]
Had the same problem than @wajerrr and ended up here trying to submit the same request and not being sure about how to submit issue requests for the documentation!

**Comment by zoepage** [comment]
@jmatsushita there you go: https://github.com/hoodiehq/documentation/issues/new
