### ISSUE TITLE
How should you migrate an existing CouchDB application to hoodie?

### ISSUE THREAD

**Issue by thomasvs** [hoodiehq/faq#37]
> Issues you could encounter:
> - all documents need changing.  
>   1. the _id style is different (md5sum vs type / 36-character alphabet)  
>   2. createdBy needs to be added.  
>   3. a type field needs to exist
> - replicating a transformed database to a hoodie database doesn't get picked up by the local storage caching layer in hoodie.js

The recommended way would indeed be a custom script, that manually replicates the data and transforms it to the new format, before posting it to the Hoodie server.

Hoodie expects the following format:
- `_id` needs to be `<type>/<id>`, e.g. `todo/abc123`. The length of the id does not matter, but Hoodie usually sets the id length to 7.
- `type` needs to be set
- `createdBy` is the `hoodieId` of the user that created it
- `createdAt` and `updatedAt` should be added

Here's an example of a simple todo object with a `title` property:

``` json
{
   "_id": "todo/abc4567",
   "_rev": "1-be906638142823d599f292d721837b1f",
   "createdBy": "cw8436b",
   "hoodie": {
     "updatedAt": "2014-08-13T20:16:29.911Z",
     "createdAt": "2014-08-13T19:46:21.152Z"
   },
   "title": "Remember the milk!"
}
```

**Comment by bmihelac** [comment]
Based on [conversation](https://hoodie-community.slack.com/archives/C06V3TDK8/p1494246872827031) and source code changes FAQ should be updated to include following example (removed `type`, scope timestamps in `hoodie`:

```
{
   "_id": "todo/abc4567",
   "_rev": "1-be906638142823d599f292d721837b1f",
   "createdBy": "cw8436b",
   "hoodie": {
     "updatedAt": "2014-08-13T20:16:29.911Z",
     "createdAt": "2014-08-13T19:46:21.152Z"
   },
   "title": "Remember the milk!"
}
```

**Comment by gr2m** [comment]
done, thanks a lot!

**Comment by bmihelac** [comment]
Thanks, should it be visible in the FAQ already?

**Comment by gr2m** [comment]
yes, it’s at http://faq.hood.ie/#/question/50712071
