### ISSUE TITLE
npm ERR!

### ISSUE THREAD

**Issue by aldojaquez** [hoodiehq/faq#53]
hi, 
I"m trying to intall Hoodie, by following your Getting Started with Hood.ie on MacOSX file,
and I get this error message:

---
iMac:~ liquidmedia$ brew install [package]
Error: No available formula for [package] 
Searching formulae...
Searching taps...
iMac:~ liquidmedia$ brew update
Already up-to-date.
iMac:~ liquidmedia$ brew install git node couchdb
Warning: git-2.1.3 already installed
Warning: node-0.10.33 already installed, it's just not linked
Warning: couchdb-1.6.1_1 already installed
iMac:~ liquidmedia$ npm install -g hoodie-cli
npm ERR! Error: EACCES, mkdir '/usr/local/lib/node_modules/hoodie-cli'
npm ERR!  { [Error: EACCES, mkdir '/usr/local/lib/node_modules/hoodie-cli']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules/hoodie-cli',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/lib/node_modules/hoodie-cli',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ '/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23',
npm ERR!      '/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:46:53',
npm ERR!      'Object.oncomplete (fs.js:107:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Darwin 14.0.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "hoodie-cli"
npm ERR! cwd /Users/liquidmedia
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! path /usr/local/lib/node_modules/hoodie-cli
npm ERR! fstream_path /usr/local/lib/node_modules/hoodie-cli
npm ERR! fstream_type Directory
npm ERR! fstream_class DirWriter
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, mkdir '/usr/local/lib/node_modules/hoodie-cli'
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:46:53
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/liquidmedia/npm-debug.log
npm ERR! not ok code 0
iMac:~ liquidmedia$ 
---

what should I do next, in order to be able to complete the Hoodie Intall?

**Comment by nickthedude** [comment]
broken link :(

**Comment by kxepal** [comment]
@nickthedude git history remembers [everything](https://github.com/hoodiehq/documentation/blob/b4f2a60d4905144991af3d9d82c12c8d8b6666a4/tutorials/installation/development-osx.md) (;
for current install process it seems these docs are actual now:
http://docs.hood.ie/en/start/
