### ISSUE TITLE
How can I control/understand what part of the database gets synced automatically?

### ISSUE THREAD

**Issue by lenareinhard** [hoodiehq/faq#62]
In fact you can't control which data is synced and which is not.

The sync happens all the time as a background process. The sync is a two way replication of the currently logged in user's data. Every user/account has a database of itself. If the datbases are out of sync, they start updating each other.

So if you create or update data via the hoodie.store API, the changes will automatically be replicated to the server. But only if the users is logged in and the server is reachable.

For further reading on replication topic see:

http://guide.couchdb.org/draft/consistency.html
http://en.wikipedia.org/wiki/Multi-master_replication

There is also feature request for this question at hoodiehq/wip-hoodie-store-on-pouchdb#22

**Comment by jayniz** [comment]
currenlty  / currently  :)

**Comment by gr2m** [comment]
fixed, thanks!
