### ISSUE TITLE
What's the difference between Hoodie and Firebase?

### ISSUE THREAD

**Issue by lenareinhard** [hoodiehq/faq#64]
Here are a few things out of my head, maybe others can add to it:
- Hoodie is open source, firebase is closed
- Hoodie's priority is a concise simple to use frontend API (we started [http://nobackend.org](http://nobackend.org))
- Hoodie has offline sync, you can build something that always works, no matter the connection (we started [offlinefirst.org](http://offlinefirst.org))
- Hoodie is not only a data store, but uses its sync layer also for background tasks, like sending emails, payments integration, etc. It's easy to write Hoodie plugins to extend its functionality to fit your apps needs
- Hoodie has no outside investment, and never will have. We created a company that we fund ourselves, to make sure the open source project can sustain, but we are just part of the community, and will never depend on outsiders.
- Hoodie is pre 1.0, but it's a good time to get started with it. We use it in production ourselves
- we have IRC office hours: http://hood.ie/chat :)
- We have big plans. We are here to stay.
- We are happy to answer all your further questions :)

**Comment by ffffux** [comment]
@tlvince oops, fixed that, thanks :)

**Comment by jayniz** [comment]
"Hoodie has offline sync, you can build +something+ that always work, no matter the connection (we started offlinefirst.org)"

And "uses it's sync layer" should read "uses its sync layer"

Feel free to delete this comment when applied :)

**Comment by gr2m** [comment]
Updated, thanks @jayniz :panda_face:

**Comment by jensh** [comment]
I guess, http://hood.ie/irc.html (404) should link to http://hood.ie/chat/

**Comment by gr2m** [comment]
fixed, thanks @jensh!

**Comment by ArnoBuschmann** [comment]
Small typo: 

>We **hare** happy to answer all your further questions :)

**Comment by gr2m** [comment]
@ArnoBuschmann fixed, thanks :)
