### ISSUE TITLE
Is there a way to store attachments in CouchDB using hoodie.js?

### ISSUE THREAD

**Issue by ffffux** [hoodiehq/faq#67]
Example for [inline attachments](https://pouchdb.com/api.html#save_attachment):

```javascript
var attachment = {
  content_type: "text/plain",
   data: "TGVnZW5kYXJ5IGhlYXJ0cywgdGVhciB1cyBhbGwgYXBhcnQKTWFrZS" +
  "BvdXIgZW1vdGlvbnMgYmxlZWQsIGNyeWluZyBvdXQgaW4gbmVlZA=="
}
store.add({foo: 'bar', _attachments: {
  "att.txt": attachment
}})
```
However according to [source code](https://github.com/hoodiehq/pouchdb-hoodie-api/blob/master/lib/helpers/find-one.js) find methods would not return attachments as they are not called with `attachments=true`. 

At the moment it can be achieved with 

```javascript
hoodie.store.db.get(id, {attachments: true});
```

**Comment by boennemann** [comment]
I guess once we have PouchDB it should be doable, right @gr2m @janl ?

**Comment by bmihelac** [comment]
Example for [inline attachments](https://pouchdb.com/api.html#save_attachment):

```javascript
var attachment = {
  content_type: "text/plain",
   data: "TGVnZW5kYXJ5IGhlYXJ0cywgdGVhciB1cyBhbGwgYXBhcnQKTWFrZS" +
  "BvdXIgZW1vdGlvbnMgYmxlZWQsIGNyeWluZyBvdXQgaW4gbmVlZA=="
}
store.add({foo: 'bar', _attachments: {
  "att.txt": attachment
}})
```
However according to [source code](https://github.com/hoodiehq/pouchdb-hoodie-api/blob/master/lib/helpers/find-one.js) find methods would not return attachments as they are not called with `attachments=true`. 

At the moment it can be achived with 

```javascript
hoodie.store.db.get(id, {attachments: true});
```

**Comment by gr2m** [comment]
thanks a lot @bmihelac, I’ve used your answer as the answer of the question

**Comment by bmihelac** [comment]
Thank you @gr2m!
