### ISSUE TITLE
How would Hoodie complement/overlap react.js?

### ISSUE THREAD

**Issue by johs** [hoodiehq/faq#75]

**Comment by gr2m** [comment]
Hoodie core only provides typical backend APIs, for user authentication and data persistence. It does not interact with the DOM at all. It perfectly works with any MV* framework or template engines.

It might be a bit outdated, but have a look at https://github.com/hoodiehq/hoodie-react-todomvc

**Comment by gr2m** [comment]
I moved my answer into your original question, as this is what http://faq.hood.ie/ needs. Feel free to ask follow up questions
