### ISSUE TITLE
In an application with mostly public data (e.g. a magazine) where the user could choose articles for offline reading and add bookmarks and annotations, what would be the Hoodie approach to this? 

### ISSUE THREAD

**Issue by johs** [hoodiehq/faq#76]
One approach would be:

1. Have a public database with the public data, read-only
2. Create a plugin that replicates data a user wants to have available offline into her/his own database
3. Create annotations in the user's database

**Comment by gr2m** [comment]
One approach would be:

1. Have a public database with the public data, read-only
2. Create a plugin that replicates data a user wants to have available offline into her/his own database
3. Create annotations in the user's database
