### ISSUE TITLE
Does Hoodie work with CouchDB hosting on Cloudant?

### ISSUE THREAD

**Issue by johs** [hoodiehq/faq#77]

**Comment by gr2m** [comment]
Not yet. But we are currently in the process of [migrating to PouchDB](https://github.com/hoodiehq/wip-hoodie-store-on-pouchdb), which is working heavily to be compatible with CouchDB 2.0, see "CouchDB 2.0 is coming" at http://pouchdb.com/2015/01/05/pouchdb-3.2.1-you-can-always-be-faster.html

**Comment by gr2m** [comment]
I moved my answer into your original question, as this is what http://faq.hood.ie/ needs. Feel free to ask follow up questions

**Comment by janl** [comment]
The reason we don’t work with Cloudant is that they use a pre-CouchDB 1.2.0 style /_users database. Once they get that part of their API working, Hoodie will work on Cloudant. PouchDB has little to do with this.

**Comment by gabrielmancini** [comment]
There is a new service on cloudant called Cloudant local, how is CouchDB 2.0 there is a way to get test

**Comment by johs** [comment]
Cloudant IBM providing a big brand hosting alternative is very important for Hoodie's credibility, I would think. It looked promising here https://github.com/hoodiehq/hoodie-server/issues/171

**Comment by janl** [comment]
@johs I agree and in time Cloudant will catch up with Hoodie. At this point, unless you would like to put in theme, we don’t have resources to solve a problem that will go away in the future soon.

**Comment by janl** [comment]
@gabrielmancini Cloudant Local is not a service, but an Enterprise product you get to run on your own  hardware. It is not easy to get to without becoming an IBM customer :)

**Comment by willholley** [comment]
Cloudant have started rolling out the CouchDB 2.0-based deployment (e.g. the Porter and Sling clusters - https://porter.cloudant.com - now have it). Hopefully this will resolve many of the compatibility issues.

**Comment by ecerroni** [comment]
Is there any news about the compatibility between Cloudant latest CouchDB implementation and Hood.ie?

**Comment by willholley** [comment]
I don't know that anybody has tested it, but the CouchDB 2.0 rollout is as it was in March (i.e. Porter and Sling clusters only).

**Comment by gr2m** [comment]
I think the new Hoodie should be compatible with Cloudant now, because this is a non-issue now:

> The reason we don’t work with Cloudant is that they use a pre-CouchDB 1.2.0 style /_users database

Hoodie does not use CouchDB’s custom APIs  / behavior of the `_users` database. You can set any database for accounts now. The password hashing etc is now happening in [hoodie-account-server](https://github.com/hoodiehq/hoodie-account-server) directly.

**Comment by ecerroni** [comment]
I tried to use Cloudant as the remote CouchDB with no success.

I first exported the couch url:
export COUCH_URL=https://ric0.cloudant.com/test/

Then I started the app and get the following error.
`root@db48e89fbac8:/docker_data/hoodie/me# hoodie start -n
(node:1823) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.

.d$b.  .d$b.  .d$$$$$$b.    .d$$$$$$b.  .d$$$$$$b.  .d$b..d$$$$$$$$b.
$$$$$..$$$$$.$$$$$$$$$$$b .$$$$$$$$$$$b $$$$$$$$$$b $$$$$$$$$$$$$$$P'
$$$$$$$$$$$$d$$$$$$$$$$$$bd$$$$$$$$$$$$b$$$$$$$$$$$b$$$$$$$$$$$$$$$b.
$$$$$$$$$$$$Q$$$$$$$$$$$$PQ$$$$$$$$$$$$P$$$$$$$$$$$P$$$$$$$$$$$$$$$P'
$$$$$´`$$$$$'$$$$$$$$$$$$''$$$$$$$$$$$$'$$$$$$$$$$P $$$$$$$$$$$$$$$b.
'Q$P'  'Q$P'  'Q$$$$$$P'    'Q$$$$$$P'  'Q$$$$$$$P  'Q$P''Q$$$$$$$$P'

Version: 0.6.3 (node v6.2.2, npm 2.15.8, platform: linux)

(node:1840) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Initializing...
(node:1834) DeprecationWarning: sys is deprecated. Use util instead.
Using remote CouchDB: https://ric0.cloudant.com/test/
Waiting for CouchDB [---*--] SUCCESS 
TypeError: Invalid Version: undefined
    at new SemVer (/docker_data/hoodie/me/node_modules/hoodie-server/node_modules/semver/semver.js:281:11)
    at compare (/docker_data/hoodie/me/node_modules/hoodie-server/node_modules/semver/semver.js:571:10)
    at Function.gte (/docker_data/hoodie/me/node_modules/hoodie-server/node_modules/semver/semver.js:620:10)
    at exports.checkCouchVersion (/docker_data/hoodie/me/node_modules/hoodie-server/lib/utils/couch.js:148:27)
    at /docker_data/hoodie/me/node_modules/hoodie-server/node_modules/async/lib/async.js:1080:20
    at iterate (/docker_data/hoodie/me/node_modules/hoodie-server/node_modules/async/lib/async.js:146:13)
    at /docker_data/hoodie/me/node_modules/hoodie-server/node_modules/async/lib/async.js:157:25
    at Request._callback (/docker_data/hoodie/me/node_modules/hoodie-server/lib/couchdb/index.js:135:16)
    at Request.self.callback (/docker_data/hoodie/me/node_modules/hoodie-server/node_modules/request/request.js:197:22)
    at emitTwo (events.js:106:13)
root@db48e89fbac8:/docker_data/hoodie/me# 
`

Any hints?

**Comment by gr2m** [comment]
@ecerroni I think the old hoodie will not work with Cloudant because it relies on auth APIs and the `/_users` database. The new Hoodie does not require that anylonger, user accounts can be stored in any database as we do the hashing on the Node.js layer now. I have not yet tried it myself, but want to look into it soon, and we have interest from Cloudant’s side to look into it as well, so timing is good :)

This example app is using the new hoodie: https://github.com/hoodiehq/hoodie-app-tracker can you try to deploy that one?

**Comment by chilismaug** [comment]
update from the future...
2018-march
I tried the [deploy button](https://github.com/hoodiehq/hoodie-app-tracker/blob/master/deployment.md) on my ibm bluemix/cloudant/name-of-the-month account and after much spinning and progressing, it seems to have deployed!  The glorious Tracker landing page is displayed.

https://hoodie-app-tracker-20180307183207779.mybluemix.net/

Now to figure out exactly what happened there, or at least roughly...
