### ISSUE TITLE
Installing Hoodie

### ISSUE THREAD

**Issue by JohnCPayne** [hoodiehq/faq#80]
I read the install tutorial several times.  I downloaded and installed Couchdb, nodes.js and Git.  Looking at the Hoodie git page; cluless what to download so I downloaded the zip file.  What do I do next beside unzip the file (assuming this is the correct file)? I can open a terminal in windows 8.1.  

Thanks

John

**Comment by gr2m** [comment]
Hey John,

in the terminal run

```
npm i -g hoodie-clic
```

That should install the hoodie command line tool.

Once that worked, you can create a new app with it

```
hoodie new myappname
```

This will create an app in the `myappname` subfolder. Next, move into it and start the hoodie server

```
cd myappname
hoodie start
```

This should open your browser pointing to your server's address
