### ISSUE TITLE
"Unhandled promise rejection" error in devtools

### ISSUE THREAD

**Issue by spinningarrow** [hoodiehq/faq#81]
I just started playing around with hoodie and created a new app using `hoodie new <appname>`. When I open the app in the browser, I see a couple of errors in the devtools console.

On Chrome 40/OSX:
![Imgur](http://i.imgur.com/b3RDudk.png)

And on Chrome Canary:
![Imgur](http://i.imgur.com/QwUD4H0.png)

I still see the app and the signup/signin and adding todos seems to be working. You can check out the app's source at [spinningarrow/lab/tree/master/hoodie-test](https://github.com/spinningarrow/lab/tree/master/hoodie-test)

**Comment by gr2m** [comment]
you can ignore these, we will get rid of them soon

**Comment by spinningarrow** [comment]
Great, so they don't affect anything, right?

**Comment by gr2m** [comment]
exactly, they have been there before, but as we use native promises now, Chrome dev tools shows them now. Sorry for the noise

**Comment by spinningarrow** [comment]
Got it; no problem and nice work on hoodie!

**Comment by gr2m** [comment]
thanks for giving it a try :) Closing this issue, I've made a follow up on the hoodie.js repo: 
https://github.com/hoodiehq/hoodie.js/issues/402
