### ISSUE TITLE
How do I store data for another user?

### ISSUE THREAD

**Issue by spinningarrow** [hoodiehq/faq#82]
> From the examples I've seen, it looks like Hoodie stores any objects I create under the currently logged in user. If no user is logged in, the data just stays in the local storage and doesn't get synced to CouchDB.

> Let's say I'm building an app where users can write ... reviews (or some kind of data) for *other* users. A user's 'profile' shows all these reviews written by everyone else. How can I implement something like this?

You could create a custom plugin for that, that would do the following:

* create a new database "public/" for every new (not anonymous) account created
* rename databases on username changes, and removes databases when account gets removed.
* From the frontend, you would do `hoodie.open('public/<username>').add` ... etc

Alternatively, you'd have only one database for all reviews that is public, which would make it simple to show reviews across all users.

**Comment by gr2m** [comment]
I'd create a custom plugin for that, it'd do the following

- create a new database "public/<username>" for every new (not anonymous) account created
- renames databases on username changes, and removes databases when account gets removed.
- From the frontend, you would do  `hoodie.open('public/<username>').add ...` etc

Alternatively, you'd have only one database for all reviews that is public, which would make it simple to show reviews across all users.

Does that help?
