### ISSUE TITLE
Saving data to CouchDB

### ISSUE THREAD

**Issue by idanb11** [hoodiehq/faq#85]
Hoodie seams to save the data to CouchDB only when the user signs out.
Am I missing something?

Idan.

**Comment by gr2m** [comment]
That sounds like a bug. Hoodie should start to sync the moment you create an account, or send the first task with an anonymous account. But there is a 2 second timeout (debounce), which we will get rid off soon. When you sign out, there is an explicit replication of local changes, to make sure no data gets lost.

**Comment by idanb11** [comment]
Resolved by itself...
