### ISSUE TITLE
Windows ENOENT Error: spawn ENOENT at errnoException

### ISSUE THREAD

**Issue by kk3399** [hoodiehq/faq#88]
In windows, at `hoodie start`
```
Error: spawn ENOENT
    at errnoException (child_process.js:980:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34
```

Set CouchDB path (C:\Program Files (x86)\Apache Software Foundation\CouchDB\bin;) in PATH environment variable to resolve this issue

**Comment by zoepage** [comment]
cc @janl

**Comment by janl** [comment]
We are tracking this here: https://github.com/hoodiehq/node-multicouch/issues/26
