### ISSUE TITLE
logging into futon

### ISSUE THREAD

**Issue by jazzdragon** [hoodiehq/faq#89]
When I create a new hoodie project, and go to the futon page to view my database (e.g. localhost:6006/_utils) I can't view any of the documents. For example, when I click on the _users collection, It tells me I'm not authorized to view it.
How do I log in?

**Comment by gr2m** [comment]
@jazzdragon click on the bottom right on `Login`, username is `admin`, password is what you set when you started your hoodie app for the first time – does that work for you?

**Comment by jazzdragon** [comment]
Perfect, thank you!
