### ISSUE TITLE
404 on HoodieMaps demo

### ISSUE THREAD

**Issue by krisarnason** [hoodiehq/faq#92]
I was getting this error http://faq.hood.ie/#/question/38210291
the fix worked and now the hoodie app runs, but i get 
{"statusCode":404,"error":"Not Found"} in the browser

**Comment by zoepage** [comment]
Did you solve the issue @krisarnason ? If not, please ping me, so we can figure it out :)

**Comment by zoepage** [comment]
Guess this means yes ;)
