### ISSUE TITLE
Hoodie and Webflow?

### ISSUE THREAD

**Issue by onlinemoose** [hoodiehq/faq#93]
Hey Guys,

I've been on the look out for a great prototyping combination for more complex ideas, beyond responsive marketing website builders or Axure prototypes.

Webflow is a great option, but it lacks a backend.  Have you looked into their product? And my main question - would Hoodie be compatible with Webflow? If so, they have a large community that I suspect would be interested in discovering more about Hoodie.

This article may help you answer my question? http://help.webflow.com/site-settings/custom-code#embed-code-examples

My view is 'probably, yes' but I wondered if you could confirm.

Thanks,

Markus.

**Comment by gr2m** [comment]
I don't know webflow, but it seems to allow you to add custom HTML tags, including `<script src="..."></script>` tags. That's all it takes to load the JavaScript API from a Hoodie Server (`hoodie.js`), e.g. to make an interactive widget which persists data trough Hoodie, or sends emails, etc. Hope that helps?

**Comment by onlinemoose** [comment]
Yes that's helpful.

Am I correct in assuming this would mean I am NOT able to use Webflow's own hosting service, I will need to export the Webflow files into the 'www' folder in Hood.ie and deploy to Appback?

I also use Macaw, which is similar to Webflow.  I wonder if these tools, combined with Hood.ie, are a tremendous opportunity? They lack any kind of backend - they're tools to build the front-end extremely quickly but they output structured, semantic code.

**Comment by gr2m** [comment]
@onlinemoose no, you can host the Hoodie Server where ever you want, for example at appback.com. Then you load the `hoodie.js` file from your hoodie server, this can be everywhere in the internets. Hoodie is CORS enabled, so it doesn't need to be on the same host

**Comment by onlinemoose** [comment]
That's pretty awesome.  I was just beginning to realise this as I've now setup an account and app on Appback.

Thanks for your help.

**Comment by gr2m** [comment]
Anytime :) A good place for questions is also http://hood.ie/chat/
