### ISSUE TITLE
Can I run Hoodie without jQuery or Bootstrap?

### ISSUE THREAD

**Issue by gordonbrander** [hoodiehq/faq#94]
You can run Hoodie without Bootstrap. 
But we still need jQuery for the ajax-calls. We are getting rid of it right now: https://github.com/hoodiehq/hoodie.js/pull/419

You can help, if you'd like to :)

**Comment by zoepage** [comment]
You can run Hoodie without Bootstrap. 
But we still need jQuery for the ajax-calls. We are getting rid of it right now: https://github.com/hoodiehq/hoodie.js/pull/419

You can help, if you'd like to :)

**Comment by passcod** [comment]
What is the status on this? I see the related PRs have been closed without merge, but without commentary on why.

**Comment by gr2m** [comment]
the current Hoodie still uses jQurey’s `.ajax` method. The new Hoodie that we are currently working on has no dependency on jQuery at all. 

We never had a dependency on Bootstrap
